[project]
name = "regression"
version = "0.1.0"
description = ""
authors = [
    {name = "antsiri",email = "antoniosirignano@outlook.it"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas (>=3.0.6,<4.0.0)",
    "scipy (>=1.18.1,<2.0.0)",
    "numpy (>=2.5.3,<3.0.0)",
    "psutil (>=7.2.2,<8.0.0)"
]

[tool.poetry]
packages = [{include = "regression", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
