[project]
name = "doe"
version = "0.1.0"
description = ""
authors = [
    {name = "antsiri",email = "antoniosirignano@outlook.it"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy (>=2.5.3,<3.0.0)",
    "statsmodels (>=0.15.0,<0.16.0)",
    "requests (>=2.34.2,<3.0.0)",
    "matplotlib (>=3.11.2,<4.0.0)",
    "seaborn (>=0.13.2,<0.14.0)"
]

[tool.poetry]
packages = [{include = "doe", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
